.github/workflows/rust.yml

name: Rust API DocsAdd commentMore actions

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rust-docs, rustfmt
      
      - name: Generate documentation
        run: cargo doc --no-deps
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
